### ISSUE TITLE
Server will need extra files 

### ISSUE THREAD

**Issue by 001scates** [jshulbs/NetworkProgramming#5]
Server relies on SQLite Database for storing peers and broadcasting messages to known peers. These are the files but they wouldn't need to be changed
protocol.h and .c for the functions that handle what is sent to the server and
database.h and .c that are databases and 
sqlscripts.h and .c that provide the text commands for the sql database
Let me know if those should be uploaded as well or if there could be a better implementation for running the commands or storing the data

**Comment by jshulbs** [comment]
If were using their code then we would need to use SQLite. Otherwise we'd have to change all the rest of it. Do you have any experience with SQLite?

**Comment by 001scates** [comment]
Sadly I had none until yesterday and today, I'm not sure if its a physical database i can easily view, but I have been able to tell how their code uses sqlite with functions in database.c and protocol.c

**Comment by jshulbs** [comment]
Okay. I've had no experience with SQLite so I've been skimming through the documentation online. I've taken a database class though so I can do queries. It looks like we just need to use SQLite to run a check and add the user if they aren't already in the database.

**Comment by 001scates** [comment]
Will it start with no known peers? And that is all we need really because that's what it has in the other solution. A check for peers and gossip and sqlite injection, then the recieve(and send) peer and gossip functions

**Comment by jshulbs** [comment]
How did their server get the names of peers? The server IP and port would be taken from the command line input so that'd be the last thing we'd need to get right?

**Comment by 001scates** [comment]
Their server would call receive_peer from the protocol.c:
void receive_peer(const char* message_buffer){
  char* name = malloc(STRING_BUFFER_MAX_LENGTH);
  char* port = malloc(STRING_BUFFER_MAX_LENGTH);
  char* address = malloc(STRING_BUFFER_MAX_LENGTH);
  int filled = sscanf(message_buffer, "PEER:%[^:]:PORT=%[^:]:IP=%[^%]%%", name, port, address);
  assert(filled == 3);
  check_for_sqlite_injection(name);
  check_for_sqlite_injection(port);
  check_for_sqlite_injection(address);
  char* command = malloc(STRING_BUFFER_MAX_LENGTH);
  int lc = snprintf(command, STRING_BUFFER_MAX_LENGTH, sql_check_for_peer_named, name);
  assert(lc < STRING_BUFFER_MAX_LENGTH);
  db_run_query(command, peer_check_if_exists_callback, 0); //from database.c that updates and checks   the sqlite database

  if (peer_exists){
    lc = snprintf(command, STRING_BUFFER_MAX_LENGTH, sql_update_existing_peer, port, address, name);
    assert(lc<STRING_BUFFER_MAX_LENGTH);
    db_run_update(command);

  }else{
    lc = snprintf(command, STRING_BUFFER_MAX_LENGTH, sql_insert_new_peer, name, port, address );
    assert(lc<STRING_BUFFER_MAX_LENGTH);
    db_run_update(command);
  }

  free(command);
  free(address);
  free(port);
  free(name);
}

**Comment by 001scates** [comment]
The server loop starts in their main.c to run over TCP and UDP only inputting a port number, but I will change ours so it will be two c files, one for TCP and UDP and then the loop can start with the port number and server ip saying which one it will be on

**Comment by jshulbs** [comment]
Truthfully we could just use that in the client too. If I'm understanding correctly, he wants it to the exact same thing.

**Comment by 001scates** [comment]
Yes the client also has to check the database and also add new peers. Should it add those functions like the server has?

**Comment by jshulbs** [comment]
That's what I would say. In my client I have an error checker function. I could probably just implement it in there after it checks to make sure the port and server IP requirements are fulfilled. The function is called every time the program is run both before TCP and UDP.

**Comment by 001scates** [comment]
Okay I'll upload those files and if we don't need something you can always take it off
